aws-cloudformation/aws-cloudformation-resource-providers-redshift-serverless

aws-redshiftserverless-namespace/aws-redshiftserverless-namespace.json
aws-redshiftserverless-namespace/docs/README.md
aws-redshiftserverless-namespace/pom.xml
aws-redshiftserverless-namespace/resource-role.yaml
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/BaseHandlerStd.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CallbackContext.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ClientBuilder.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CreateHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/DeleteHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/Translator.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateHandler.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/AbstractTestBase.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/CreateHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/DeleteHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/ReadHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/UpdateHandlerTest.java

Integrating Redshift Resource Policy with Redshift Serverless Namespace.
1. Once the Namespace is created and in active stage, Resource Policy will be attached to Namespace if the resource policy is included with templates while creating the namespace.
2. Resource policy can be modified or deleted using Cfn Update handler.

Resource Policy Integration with Namespace

---

aws-redshiftserverless-namespace/aws-redshiftserverless-namespace.json
aws-redshiftserverless-namespace/docs/README.md
aws-redshiftserverless-namespace/pom.xml
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/Translator.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateHandler.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/AbstractTestBase.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/CreateHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/UpdateHandlerTest.java

The changes provide Cloudformation support for Secrets Manager integration with Redshift Serverless. With this new feature, customers can opt in to store their namespace's admin credentials in a service linked secret in Secrets Manager. It allows us to create/modify Redshift Serverless namespaces with Secrets Manager support using the Cloudformation template. The changes in this request allow us to use create-namespace and update-namespace APIs for Redshift Serverless namespaces when opting in to this feature.
We are adding a new boolean parameter "ManageAdminPassword" to allow customers to opt in to this feature and another parameter "AdminPasswordSecretKmsKeyId" allows customers to specify the key ID of the KMS key in the customer account which will be used to encrypt the namespace's …

Cloudformation support for Secrets Manager Integration

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/Translator.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateHandler.java

1. Read Handler - NoOp method for handling GetresourcePolicy Exceptions - this method will assign empty value to NamespaceResourcePolicy if there are permission issues that restrict accessing GetResourcePolicy API. Also, empty value is assigned if NamespaceResourcePolicy is not found on the Namespace. Assigning empty value will suppress NamespaceResourcePolicy property in CreateCluster Cfn response.
2. Translator - Update logger to handle empty NamespaceResourcePolicy.
3. Update Handler - Rename CallGraph name to avoid conflicts with Read Handler CallGraph name.

No-Op method for handling GetResourcePolicy exceptions.

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java

ResourcePolicy API is not enabled in all the regions. We need to handle unsupported exceptions in regions where this API is not supported.

Handle Unsupported ResourcePolicy Exceptions.

---

aws-redshiftserverless-workgroup/aws-redshiftserverless-workgroup.json

This CR contains schema changes required to deploy workgroup. Resource Policy changes added an extra call to get workgroup which would need schema changes as new endpoint permissions are required.
Testing:
1. Build artifacts and copy to your bucket ```bash bb && cp <Packagefolder>/build/packaging_additional_published_artifacts/ ```
2. Local Contract Tests expect credentials to be present in terminal before execution. ```bash export ISENGARD_PRODUCTION_ACCOUNT=false export AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID> export AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY> export AWS_SESSION_TOKEN=<AWS_SESSION_TOKEN> ```
3. Run a docker image that deploys resources to run CTV2 in your account ```bash docker run --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \ --env …
```

Schema changes required to deploy workgroup

---

aws-redshiftserverless-namespace/README.md
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CreateHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java

Added fix for namespace create not throwing error if resource already exists. This is because event progress is not updated after call to create namespace.Updating the progress to event call fixes the issue.
Also updated README.md to reflect resource development guide and checks.
Replication Steps:
1. Create a resource with cli. 
2. cfn stack deploy with same namespace name
3. This doesn't throw error before but throws error after this fix.

Fix for namespace create not throwing error if resource already exists

---

aws-redshiftserverless-workgroup/.rpdk-config
aws-redshiftserverless-workgroup/aws-redshiftserverless-workgroup.json
aws-redshiftserverless-workgroup/docs/README.md
aws-redshiftserverless-workgroup/docs/configparameter.md
aws-redshiftserverless-workgroup/docs/tag.md
aws-redshiftserverless-workgroup/docs/workgroup.md
aws-redshiftserverless-workgroup/resource-role.yaml

This change contains schema changes for dependencies to deploy. This is required because during build schema permissions are converted to resource-role which is used to execute contract tests.The same permissions apply to deployment of dependencies as well. CT dependencies deployment uses the same role created in resource-role.yaml

Modified schema permissions for workgroup dependencies to deploy

---

aws-redshiftserverless-namespace/.rpdk-config
aws-redshiftserverless-workgroup/.rpdk-config

This commit reverts rpdk config changes from previous commit. The previous commit overrides contract test role policy causing contract to fail.

Reverting rpdk config file changes

---

aws-redshiftserverless-namespace/.rpdk-config
aws-redshiftserverless-namespace/template.yml

Upgrade CFN resources runtime to JDK17 from JDK8 as JDK8 is on deprecation path

Upgrade CFN resources runtime to JDK17

---

aws-redshiftserverless-workgroup/.rpdk-config
aws-redshiftserverless-workgroup/template.yml

Security Compliance dictates to upgrade the JDK runtime version for resources to be upgraded from JDK8. This CR contains the change for runtime upgrade from JDK8 to JDK17.
Testing:
1. Local contract test passing with latest JDK17 upgrade.
2. Local Handler invocation passed successfully.

JDK17 runtime upgrde for workgroup resource

---

aws-redshiftserverless-namespace/pom.xml
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/ReadHandlerTest.java

Our CFN handler needs getResourcePolicy permission to see if resource-policy is created or not, but at the same time we need to support existing customers who don't have this permission, so we added some error catching logic to be backward compatible.
Turns out the previous exception catching logic is not sufficient to catch all customer exceptions.
This commit catches all exceptions when resourcePolicy is not present, to unblock all existing customers who are not using resourcePolicy issue. Our team will evaluate and restrict the catching logic if needed

Catch all exceptions when resourcePolicy is not present

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/ReadHandlerTest.java

Fixed merge conflicts
*Testing*
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --< software.amazon.redshiftserverless.namespace:aws-redshiftserverless-namespace-handler >--
[INFO] Building aws-redshiftserverless-namespace-handler 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jacoco:0.8.4:prepare-agent (default) @ aws-redshiftserverless-namespace-handler ---
[INFO] argLine set to -javaagent:/Users/donwimo/.m2/repository/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4-runtime.jar=destfile=/Volumes/workplace/aws-cloudformation-resource-providers-redshift-serverless/aws-redshiftserverless-namespace/target/jacoco.exec,excludes=**/BaseConfigurati …
```

Resolved merge conflict with revert #47

---

aws-redshiftserverless-workgroup/.rpdk-config
aws-redshiftserverless-workgroup/pom.xml
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/BaseHandlerStd.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/CallbackContext.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/CreateHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/ReadHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/UpdateHandler.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/CreateHandlerTest.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/ReadHandlerTest.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/UpdateHandlerTest.java

In eu-north-1 region, some wf steps take longer to finish, and contract test would fail because of ConflictException("There is an operation running on the workgroup") and contract test will fail.
This commit handles the exception by matching the exception message and retry on the exception, giving the wf more time to finish.

Retry create/update on workgroup conflict exception

---

aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/CreateHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/UpdateHandler.java

When running tests in prod eu-north-1, we keep running into the same issue that was resolved during local test run. Before we can fix the issue in backend, we'll increase the handler retries to succeed the operation.

Increase wg busy max retries to 5

---

aws-redshiftserverless-workgroup/aws-redshiftserverless-workgroup.json
aws-redshiftserverless-workgroup/resource-role.yaml
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/BaseHandlerStd.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/CreateHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/DeleteHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/ReadHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/Translator.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/UpdateHandler.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/AbstractTestBase.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/CreateHandlerTest.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/DeleteHandlerTest.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/ReadHandlerTest.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/UpdateHandlerTest.java

Description: This CR contains fix for stabilization not correctly implemented for Workgroup Resource. During Read handler we are returing in Progress status which is not allowed. This CR will fix that issue.
Currently as part of create and delete handlers we are only checking if Workgroup is stablized. This is causing failures if the same workgroup is created immediately causing "Operation in progress failure". This is because Namespace is not stabilized during the operation. This CR fixes that issue as well.
Testing:
1. Tested if CTV2 is passing in eu-north-1 and us-west-1 region which are currently failing CTV2 for Workgroup resource.
2. Verified CTV2 is passing for those regions in personal account.
By submitting this pull request, I …

Fix for Workgroup stabilization failures on operations

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/DeleteHandler.java

Contract tests are failing for Namespace because we get the error "Unable to update admin credentials: Unable to create secret for the dbInstance because a secret with a matching name exists". This is happening because delete namespace performs a delete secret operation when managed passwords is called causing the secret to be deleted asynchronously.
As part of CTV2 as these tests use the same cluster identifier it causes the creation of secret with same name in the subsequent test even before the secret can get deleted completed in previous test. This delay is added as a temporary fix to stabilize the operation until the permanent fix to stabilize the operation based on the secret operation is done 
By submitting this pull request, I …

Added a 10sec delay in delete handler to help with stabilization of secret deletion

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/DeleteHandler.java

We are changing the wait time after delete to 30secs as Ctv2 was still failing in few regions with secret already exists.
As part of CTv2 CFN runs tests which use the same cluster identifier. Managed passwords uses this identifier to create secrets and reusing the same identifier in tests back to back causes resource conflict exception

Modified the wait after delete to be 30secs from 10 secs

---

aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/DeleteHandler.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/BaseHandlerStd.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/CallbackContext.java
aws-redshiftserverless-workgroup/src/main/java/software/amazon/redshiftserverless/workgroup/DeleteHandler.java
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/DeleteHandlerTest.java

Uluru framework provides an option of introducing delays in operation through eventual consistency model. This gives an option to run the operation with an option to progress after a certain delay for operations that are eventually consistent. This pull request contains changes for the above feature. This is needed as CTv2 tests were failing with operation in progress failure on workgroup. 

Fix for delete handler eventual consistency

---

aws-redshiftserverless-namespace/.rpdk-config
aws-redshiftserverless-namespace/README.md
aws-redshiftserverless-namespace/docs/namespace.md
aws-redshiftserverless-namespace/docs/tag.md
aws-redshiftserverless-namespace/pom.xml
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/BaseHandlerStd.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CallbackContext.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ClientBuilder.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CreateHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/DeleteHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateHandler.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/CreateHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/DeleteHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/ReadHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/UpdateHandlerTest.java
aws-redshiftserverless-namespace/template.yml
aws-redshiftserverless-workgroup/docs/README.md
aws-redshiftserverless-workgroup/docs/configparameter.md
aws-redshiftserverless-workgroup/docs/tag.md
aws-redshiftserverless-workgroup/docs/workgroup.md
aws-redshiftserverless-workgroup/src/test/java/software/amazon/redshiftserverless/workgroup/DeleteHandlerTest.java

- Remove 30 seconds wait after namespace deletion in namespace delete handler 
- Add secrets manager dependency and client
- Modify the stabilize operation for namespace delete handler to verify that the secret associated with the namespace is deleted 
[Testing]
- Unit Tests
- Manually tested that deletion of following namespaces followed expected behaviour
- Namespace without secret -> Deleted successfully
- Namespace with secret and default key -> Deleted successfully
- Namespace with secret and customer managed key -> Deleted successfully
- Above three cases with workgroup attached. Delete workgroup and then namespace -> Deleted successfully 
- Invalid Namespace -> Returns NotFound Error
By submitting this pull request, I confirm that …

Wait for secret deletion in the stabilize operation of namespace delete handler

---

aws-redshiftserverless-namespace/aws-redshiftserverless-namespace.json
aws-redshiftserverless-namespace/resource-role.yaml
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/BaseHandlerStd.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/CreateHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/ReadHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/Translator.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateHandler.java
aws-redshiftserverless-namespace/src/main/java/software/amazon/redshiftserverless/namespace/UpdateTagsRequest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/AbstractTestBase.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/CreateHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/ReadHandlerTest.java
aws-redshiftserverless-namespace/src/test/java/software/amazon/redshiftserverless/namespace/UpdateHandlerTest.java

- This CR contains changes related to supporting tags during update namespace operation. Currently Namespace supports tags during create namespace operation only. We are not able to update tags as the update handler does not support updating the tags.
- This CR also fixes the current issue with contract test failing because they expect the resources which support tagging to include the permissions for tagging operations to work. 
[Testing]
Unit Tests
Manually tested that deletion of following namespaces followed expected behaviour
Executed handlers using local sam cli
Executed contract tests and verified that they pass
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Fix for Update Operation to update tags Support for Namespace

---

aws-redshiftserverless-workgroup/aws-redshiftserverless-workgroup.json
aws-redshiftserverless-workgroup/docs/configparameter.md
aws-redshiftserverless-workgroup/docs/performancetarget.md
aws-redshiftserverless-workgroup/docs/tag.md
aws-redshiftserverless-workgroup/docs/workgroup.md

Current usage of GetAtt with BaseCapacity and MaxCapacity is broken.
Removed both of these from WriteOnly Properties and allowed all properties to use GetAtt, not just those in ReadOnly.
Confirmed successful contract test with these changes.

Fix GetAtt Usage with BaseCapacity and MaxCapacity
